### PR TITLE
Fix: Momentum scrolling continues despite press and hold in list view

### LINKED ISSUE #190: Momentum scrolling continues despite press and hold in list view if items are clickable
In the video you can see the sheet passing through tap gesture without stopping the scroll.
I also included a fullscreen implementation to show how it should behave.

Versions:
smooth_sheets: 0.8.1
go_router: 14.2.0

[![Video]](https://github.com/fujidaiti/smooth_sheets/assets/63209580/68147a6a-818e-4553-b251-91b73458a46f)

<details><summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:smooth_sheets/smooth_sheets.dart';

void main() {
  runApp(MyApp());
}

final transitionObserver = NavigationSheetTransitionObserver();

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final router = GoRouter(
    initialLocation: "/sheet",
    routes: [
      ShellRoute(
        observers: [transitionObserver],
        builder: (context, state, child) {
          return NavigationSheet(
            transitionObserver: transitionObserver,
            child: Material(
              color: Theme.of(context).colorScheme.primary,
              borderRadius: BorderRadius.circular(16),
              clipBehavior: Clip.antiAlias,
              child: child,
            ),
          );
        },
        routes: [
          GoRoute(
            path: "/sheet",
            pageBuilder: (context, state) {
              return ScrollableNavigationSheetPage(
                key: state.pageKey,
                initialExtent: const Extent.proportional(0.9),
                minExtent: const Extent.proportional(0.9),
                maxExtent: const Extent.proportional(0.9),
                child: PageBlue(),
                transitionsBuilder: (context, animation, secondaryAnimation, child) {
                  final theme = Theme.of(context).pageTransitionsTheme;
                  final route = ModalRoute.of(context) as PageRoute<dynamic>;
                  return theme.buildTransitions(route, context, animation, secondaryAnimation, child);
                },
              );
            },
          ),
        ],
      ),
      GoRoute(
        path: "/fullscreen",
        pageBuilder: (context, state) {
          return MaterialPage(child: PageGreen());
        },
      )
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
    );
  }
}

class PageBlue extends StatelessWidget {
  final List<String> items = List<String>.generate(50, (index) => "Item ${index + 1}");

  PageBlue({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sheet'),
        backgroundColor: Colors.blue,
        actions: [
          TextButton(
            onPressed: () => context.go("/fullscreen"),
            child: const Text("to FullScreen"),
          )
        ],
      ),
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) {
          return InkWell(
            onTap: () {},
            child: ListTile(
              title: Text(items[index]),
            ),
          );
        },
      ),
    );
  }
}

class PageGreen extends StatelessWidget {
  final List<String> items = List<String>.generate(50, (index) => "Item ${index + 1}");

  PageGreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('FullScreen'),
        backgroundColor: Colors.green,
        actions: [
          TextButton(
            onPressed: () => context.go("/sheet"),
            child: const Text("to Sheet"),
          )
        ],
      ),
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (context, index) {
          return InkWell(
            onTap: () {},
            child: ListTile(
              title: Text(items[index]),
            ),
          );
        },
      ),
    );
  }
}

```

</details>

### PR DESCRIPTION
**Pull request by fujidaiti**
## Fixes / Closes (optional)

Fixes #190.

## Description

This PR fixes an incorrect use of the `ScrollActivity.shouldIgnorePointer` flag that has caused the issue.

Previously, `DragScrollDrivenSheetActivity` used to start a `SheetContentBallisticScrollActivity` with `shouldIgnorePointer` set to `false` when a drag gesture ended. However, it should actually be `true` except in a special case. This is because setting `ScrollActivity.shouldIgnorePointer` to `true` means that clickable items in the scroll view cannot receive pointer events while performing that activity, and the scroll view may receive them instead. So if the flag is set to `false` during a ballistic scroll animation and there are any clickable items in the scroll view, the scroll view may not be able to receive the pointer events, resulting in the ballistic scroll animation not stopping in response to user gestures.

After this PR is merged, `SheetContentBallisticScrollActivity` will be started with the same value of `shouldIgnorePointer` as the previous `ScrollActivity`. Note that we can't use a hardcoded value of `true` here, as it may need to be `false` in a special case where the pointer device kind is `PointerDeviceKind.trackpad`.

## Summary (check all that apply)

- [x] Modified / added code
- [x] Modified / added tests
- [ ] Modified / added examples
- [ ] Modified / added others (pubspec.yaml, workflows, etc...)
- [ ] Updated README
- [ ] Contains breaking changes
  - [ ] Created / updated migration guide
- [ ] Incremented version number
  - [ ] Updated CHANGELOG

### CODE REVIEW

File: package/lib/src/scrollable/scrollable_sheet_activity.dart [hunk 1]
```diff
@@ -187,7 +187,7 @@ class DragScrollDrivenSheetActivity extends ScrollableSheetActivity
   void applyUserDragEnd(Velocity velocity) {
     owner.goBallisticWithScrollPosition(
       velocity: -1 * velocity.pixelsPerSecond.dy,
-      shouldIgnorePointer: false,
+      shouldIgnorePointer: true,
```
Comment (fujidaiti) [inline package/lib/src/scrollable/scrollable_sheet_activity.dart:190]: Once #166 is closed, use `SheetActivity.ignorePointer` instead.
