### PR TITLE
Fix crash when getting attached controller from sub-tree

### LINKED ISSUE #151: Attaching SheetController to NavigationSheet causes "Null check operator used on a null value"
### Discussed in https://github.com/fujidaiti/smooth_sheets/discussions/143

<div type='discussions-op-text'>

<sup>Originally posted by **andikatp** May 30, 2024</sup>
Im stuck and not sure how to add controller to ScrollableNavigationSheetRoute, i want to create an animation where the border radius at top left and right to zero when it reaches the top of the page, usually i listen to height of the modal using controller, but i dont know how to put controller in ScrollableNavigationSheetRoute, thanks</div>

Reproduction code: https://github.com/fujidaiti/smooth_sheets/discussions/143#discussioncomment-9606634

### PR DESCRIPTION
**Pull request by fujidaiti**
Fixed #151.

Manually reverted #102 to remove `ImplicitSheetControllerScope` which is the cause of #151 and is no longer needed at this time.

### CODE REVIEW

File: package/test/navigation/navigation_sheet_test.dart [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+
+void main() {
+  late NavigationSheetTransitionObserver transitionObserver;
+
+  setUp(() {
+    transitionObserver = NavigationSheetTransitionObserver();
+  });
+
+  testWidgets(
+    'Attached controller emits correct pixel values when dragging sheet',
```
Comment (fujidaiti) [inline package/test/navigation/navigation_sheet_test.dart]: Remove `sheet` at the last

File: cookbook/lib/issue/issue151.dart [hunk 2]
```diff
@@ -0,0 +1,81 @@
+import 'package:flutter/material.dart';
+import 'package:smooth_sheets/smooth_sheets.dart';
+
+/// Issue [#151](https://github.com/fujidaiti/smooth_sheets/issues/151):
+/// Attaching SheetController to NavigationSheet causes
+/// "Null check operator used on a null value"
+void main() {
```
Comment (fujidaiti) [inline cookbook/lib/issue/issue151.dart]: Remove this file since we have a widget test for this problem.
